

SELECT * FROM Traffic_Crashes2018 WHERE (VEHICLE_TYPE = 'SNOWMOBILE') or (VEHICLE_TYPE = 'FARM EQUIPMENT');


SELECT * from Traffic_Crashes2018 WHERE (VEHICLE_YEAR % 5 == 0) and (LIC_PLATE_STATE != 'IL');

SELECT * FROM Traffic_Crashes2018 where (UNIT_NO % 2 == 0) and (VEHICLE_YEAR % 2 == 1) and (VEHICLE_YEAR >  2010);

SELECT * FROM Traffic_Crashes2018 WHERE (CRASH_DATE = '11/10/2017') AND (VEHICLE_YEAR < 2000);

SELECT FIRST_CONTACT_POINT,VEHICLE_TYPE,MAKE,MODEL from Traffic_Crashes2018 where (FIRST_CONTACT_POINT != 'UNKNOWN') AND (FIRST_CONTACT_POINT != 'FRONT') AND (FIRST_CONTACT_POINT != 'NONE') AND (FIRST_CONTACT_POINT != 'REAR') AND (MAKE = 'NISSAN') AND (VEHICLE_TYPE = 'PICKUP');

SELECT * FROM Traffic_Crashes2018 WHERE (MANEUVER = 'DRIVING WRONG WAY') AND (MODEL = 'COROLLA');

